### PR TITLE
fix: index: add support of acorn v7

### PR DESCRIPTION
**Pull request by coderaiser**
Add ability to not crash on `acorn` v7 (acornjs/acorn#862)

### CODE REVIEW

**Comment by LongTengDao** [comment]
Remember the pkg.peerDependencies.

And, are you sure the code is compatible infact?

**Comment by coderaiser** [comment]
@LongTengDao, yes this code compatible, changes of `acorn v7` touches [dynamic imports mostly](https://github.com/acornjs/acorn/blob/master/acorn/CHANGELOG.md#700-2019-08-13).

I use `acorn` with `stage3` in [putout](https://github.com/coderaiser/putout) and just add support of it to [estree-to-babel](https://github.com/coderaiser/estree-to-babel) with https://github.com/coderaiser/estree-to-babel/commit/0e78a5f6054605f2b06b8b888df1395e6e601af7, everything works good :).

And tests are passing.

**Comment by LongTengDao** [comment]
@coderaiser Thank you

BTW: `"acorn": "^6.1.0 || ^7.0.0",` would be better.

**Comment by coderaiser** [comment]
@LongTengDao updated and wandering are you maintainer 🙂? When this will be merged?

**Comment by LongTengDao** [comment]
I'm user @marijnh

**Comment by marijnh** [comment]
Merged as 635d7ad

**Pull request closed without merging**
